### ISSUE TITLE
Publish new gem version 

### ISSUE THREAD

**Issue by iaintshine** [opentracing/opentracing-ruby#15]
@bhs can u pls publish new version of the gem, as in the 0.3.0 `Span` still has `initialize` method with 2 required attributes. It was removed in this [commit](https://github.com/opentracing/opentracing-ruby/commit/afdb6150e7ae92069f1c421897cc2fb4989b4e8f#diff-057529a22c640ae222b05371aac4e250). Thanks in advance.

**Comment by bhs** [comment]
Done. Thanks for bringing this up.
