### ISSUE TITLE
Make logging consistent w/other libraries

### ISSUE THREAD

**Issue by itsderek23** [opentracing/opentracing-ruby#22]
In #4, a side-thread started on cleaning up the logging-related methods. There are some inconsistencies with other language implementations of OpenTracing. 

@edithau nicely summarized logging implementations :clap:. I've copied this below:

### Go

* logKv - method signature: a list of String KV-pairs
* logFields - method signature: a list of string keys & String/Num/Bool values

### Python

* log_kv - method signature: a list of String KV-pairs
* log - method signature: String (deprecated)

### Java

* log  - method signature: a list of String keys & String/Num/Bool values
* log - method signature: String 

Note: The Java implementation recommends the standard fields mentioned in the spec's Log fields table section. But did not really do much with it

## Proposed Next Steps

@edithau suggests the following for Ruby:

* `log_kv` - method signature: String KV-pairs 
* `log` - method signature: String (seems like it’s a good idea to have such a convenience method.  
Not sure why only Java supports it and Python deprecates it)

**Comment by itsderek23** [comment]
> log - method signature: String (seems like it’s a good idea to have such a convenience method.
Not sure why only Java supports it and Python deprecates it)

Hmm - it looks like the [specification says](https://github.com/opentracing/specification/blob/master/specification.md#log-structured-data) that "One or more key:value pairs" are required params. I didn't see anything specific in the blame history for why this was deprecated in Python (I'm guessing this was the cause).

I'll dig around for more on `log`. That said, it seems like `log_kv` is a no-brainer

**Comment by edithau** [comment]
I agree.  Java's `log(string)` is the shorthand for `log_kv("event" => "event value...")`  The spec has [multiple standard log fields](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#log-fields-table) with type `String`,  it may be a bit confusing to shorthand `log` to 'event' type. 

@itsderek23  I can submit a PR to deprecate `log` and add `log_kv`.  Let me know your thought.  Thanks! :)

**Comment by itsderek23** [comment]
> I can submit a PR to deprecate log and add log_kv. Let me know your thoughts. Thanks! :)

Makes sense to me!

I'm guessing a `#warn` inside the existing `log` method is the best approach?

**Comment by indrekj** [comment]
log_kv has been implemented. Can we close this?
