### ISSUE TITLE
Add additional gem owners

### ISSUE THREAD

**Issue by itsderek23** [opentracing/opentracing-ruby#32]
I believe @bhs, @mytrile, and myself are the [current opentracing gem owners](https://rubygems.org/gems/opentracing). It'd be great to get another Rubyist onboard to cut releases and keep momentum going.

@mwear and @indrekj - any interest in being added as owners? You've made nice contributions / reviews / code comments.

**Comment by mwear** [comment]
I wouldn't mind being added so that I can help out with releases.

**Comment by bhs** [comment]
@indrekj what's your rubygems.org username? @mwear I just added you. thanks!

**Comment by bhs** [comment]
@indrekj nevermind – Google was able to help me with this :)

I'll close this issue as I think we're done. Clearly I'm mostly useless as far as Ruby is concerned, but I'll leave myself as an owner just for redundancy if that's ok.
