### ISSUE TITLE
Can master be published as a gem?

### ISSUE THREAD

**Issue by ethanjcohen-underarmour** [opentracing/opentracing-ruby#37]
It looks like the latest tag/gem is 0.4.1, which differs quite a bit from what is on master. For proper distributed tracing I need access to the `active_span` but the `0.4.x` API doesn't allow for that.

Can master be published, or can someone tell me how to identify the active span to use as a parent, in my ruby code?

Thanks!

**Comment by mwear** [comment]
Hi @ethanjcohen-underarmour. Thanks for bringing this up. In `0.4.1` there is an `active_span` method on the global tracer. It was moved to Tracer in [this commit](https://github.com/opentracing/opentracing-ruby/commits/master), which is probably what you're looking for. I will publish master as `0.4.2` soon.

**Comment by mwear** [comment]
@ethanjcohen-underarmour: v0.4.2 is now live on RubyGems

**Comment by ethanjcohen-underarmour** [comment]
Then maybe the issue is that the readme is wrong, that's what I was going off of initially.

It shows `OpenTracing.active_span` as an example, but it should be `OpenTracing.global_tracer.active_span` right?

**Comment by mwear** [comment]
Both of those lines are equivalent, see [here](https://github.com/opentracing/opentracing-ruby/blob/master/lib/opentracing.rb#L39-L40). There are delegators defined on the OpenTracing module that forward to the `global_tracer`.

**Comment by ethanjcohen-underarmour** [comment]
I saw that but thought it wasn't published. Looks good now, regardless. Thanks!

**Comment by mwear** [comment]
Master was published as v0.4.2 moments ago: https://rubygems.org/gems/opentracing/versions/0.4.2. Let me know if there's anything else I can help with.
