### ISSUE TITLE
`event` should not be a required parameter to `Span.log`

### ISSUE THREAD

**Issue by bhs** [opentracing/opentracing-ruby#4]
https://github.com/opentracing/opentracing-ruby/blob/master/lib/opentracing/span.rb#L51

Issue title says it all... `event` is a "standard" logging field, but should not be a required logging field.

**Comment by edithau** [comment]
Hi, I would like to fix this bug but I realize the the `span` class is just a skeleton right now.    What would be the best way to contribute?  Should I just fix the `log` method signature or should I provide the `log` implementation as well?  Any suggestion?

**Comment by itsderek23** [comment]
Hi @edithau - thx for the offer!

My thoughts:

To quickly get this in gear, I think simply updating the method signature works. 

It seems like we need a separate PR to get the `Span` logic implemented.

**Comment by edithau** [comment]
Hi @itsderek23, thanks for the quick response!   Will tag you on the signature update PR. :)

A separate PR is a great idea.  Should I submit an issue first to get things going.  Let me know

**Comment by itsderek23** [comment]
> 

> Hi @itsderek23, thanks for the quick response! Will tag you on the signature update PR. :)

👍 

> Should I submit an issue first to get things going?

Good question! I took a look at [opentracing-python](https://github.com/opentracing/opentracing-python/blob/master/opentracing/span.py) to see what is implemented for `Span`.

It looks like there are 2 log-related methods in the Python `Span` class:

* log
* log_kv

[Go has 2](https://github.com/opentracing/opentracing-go/blob/master/span.go#L117):

* LogFields
* LogKV

I haven't looked thru the code yet to see what makes sense for Ruby.

**Comment by edithau** [comment]
Hi, @itsderek23  here is what I found.   Let me know your thought!

Go:
```
logKv - method signature: a list of String KV-pairs
logFields - method signature: a list of string keys & String/Num/Bool values
```

Python:
```
log_kv - method signature: a list of String KV-pairs
log - method signature: String (deprecated)
```

Java:
```
log  - method signature: a list of String keys & String/Num/Bool values
log - method signature: String 
```
Note: The Java implementation recommends the standard fields mentioned in the [spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md)'s Log fields table section.  But did not really do much with it 

**So for Ruby, here’s what I’m thinking**
```
log_kv - method signature: String KV-pairs 
log - method signature: String 
(seems like it’s a good idea to have such a convenience method.  
Not sure why only Java supports it and Python deprecates it)
```

**Comment by itsderek23** [comment]
Discussion on appropiate log methods for Ruby moved to #22.

**Comment by indrekj** [comment]
log_kv has been implented. Can we close this?
